-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 23:40:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`History study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`History study` ;

CREATE TABLE IF NOT EXISTS `mydb`.`History study` (
  `idHistory study` INT NOT NULL,
  `Student_Student_id` INT NOT NULL,
  `class_idclass` INT NOT NULL,
  `term_idterm` INT NOT NULL,
  PRIMARY KEY (`idHistory study`, `Student_Student_id`, `class_idclass`, `term_idterm`),
  CONSTRAINT `fk_History study_Student`
    FOREIGN KEY (`Student_Student_id`)
    REFERENCES `mydb`.`Student` (`Student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_History study_class1`
    FOREIGN KEY (`class_idclass`)
    REFERENCES `mydb`.`class` (`idclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_History study_term1`
    FOREIGN KEY (`term_idterm`)
    REFERENCES `mydb`.`year` (`idterm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professer` (
  `idProfesser` INT NOT NULL,
  `Subject_idSubject` INT NOT NULL,
  PRIMARY KEY (`idProfesser`, `Subject_idSubject`),
  CONSTRAINT `fk_Professer_Subject1`
    FOREIGN KEY (`Subject_idSubject`)
    REFERENCES `mydb`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `Student_id` INT NOT NULL,
  `Student_name` VARCHAR(45) NOT NULL,
  `Student_class` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `idSubject` INT NOT NULL,
  PRIMARY KEY (`idSubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`class` ;

CREATE TABLE IF NOT EXISTS `mydb`.`class` (
  `idclass` INT NOT NULL,
  `class_room` VARCHAR(45) NOT NULL,
  `class_name` VARCHAR(45) NOT NULL,
  `tablestudy_idtablestudy` INT NOT NULL,
  PRIMARY KEY (`idclass`, `tablestudy_idtablestudy`),
  CONSTRAINT `fk_class_tablestudy1`
    FOREIGN KEY (`tablestudy_idtablestudy`)
    REFERENCES `mydb`.`tablestudy` (`idtablestudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detailTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detailTable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detailTable` (
  `iddetailTable` INT NOT NULL,
  `detail_name` VARCHAR(45) NULL,
  `tablestudy_idtablestudy` INT NOT NULL,
  `Subject_idSubject` INT NOT NULL,
  PRIMARY KEY (`iddetailTable`, `tablestudy_idtablestudy`, `Subject_idSubject`),
  CONSTRAINT `fk_detailTable_tablestudy1`
    FOREIGN KEY (`tablestudy_idtablestudy`)
    REFERENCES `mydb`.`tablestudy` (`idtablestudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detailTable_Subject1`
    FOREIGN KEY (`Subject_idSubject`)
    REFERENCES `mydb`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tablestudy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tablestudy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tablestudy` (
  `idtablestudy` INT NOT NULL,
  PRIMARY KEY (`idtablestudy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`year` ;

CREATE TABLE IF NOT EXISTS `mydb`.`year` (
  `idterm` INT NOT NULL,
  `year_name` INT NOT NULL,
  `tablestudy_idtablestudy` INT NOT NULL,
  PRIMARY KEY (`idterm`, `tablestudy_idtablestudy`),
  CONSTRAINT `fk_year_tablestudy1`
    FOREIGN KEY (`tablestudy_idtablestudy`)
    REFERENCES `mydb`.`tablestudy` (`idtablestudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
